import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <nav className="w-full bg-zinc-900 text-white px-8 py-4 flex items-center justify-between">
          <div className="font-bold text-lg">
            Quantity Estimate
          </div>
          <div className="flex gap-6">
            <a href="/" className="hover:underline">Home</a>
            <a href="/grid" className="hover:underline">Grid System</a>
            <a href="/estimates" className="hover:underline">Estimates</a>
          </div>
        </nav>
        <div className="pt-4">{children}</div>
      </body>
    </html>
  );
}
